# Production environment
version: "3.9"

services:
  frontend:
    image: ghcr.io/nismod/jsrat-frontend:0.1
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    image: ghcr.io/nismod/jsrat-backend:0.1
    build: ./backend
    ports:
      - "3001:80"
    env_file:
      - ./envs/prod/.backend.env

  vector-tileserver:
    image: ghcr.io/nismod/jsrat-vector-tileserver:0.1
    build:
      context: ./tileserver/vector
      dockerfile: prod.Dockerfile
    ports:
      - "3002:8080"
    volumes:
      - ./tileserver/vector/data:/data
      - ./tileserver/vector/config.json:/config.json

  raster-tileserver:
    image: ghcr.io/nismod/jsrat-raster-tileserver:0.1
    build: ./tileserver/raster
    ports:
      - "3003:5000"
    volumes:
      - ./tileserver/raster/data:/data
      - ./tileserver/raster/config.toml:/config.toml
    environment:
      - TC_DRIVER_PATH=/data/terracotta.sqlite
      - TC_RESAMPLING_METHOD=nearest
      - TC_REPROJECTION_METHOD=nearest
      - TC_PNG_COMPRESS_LEVEL=1
