# multistage build of nginx image

# stage 1 of 2
FROM node:16 AS builder
WORKDIR /app

COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm ci

COPY frontend .
RUN npm run build

# stage 2 of 2
FROM nginx:alpine
# add package containing htpasswd utility
RUN apk update && apk add apache2-utils
WORKDIR /usr/share/nginx/html
# remove default nginx static assets
RUN rm -rf ./*
# copy in static assets from builder stage
COPY --from=builder /app/build* .
# and copy in the nginx config...
# delete conf.d as it will contain default.conf which will conflict
RUN rm -rf /etc/nginx/conf.d
COPY nginx/prod /etc/nginx
# SSL Certs mounted externally

# containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
